In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')

In [3]:
credits=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.shape

(4803, 20)

In [5]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [6]:
credits.shape

(4803, 4)

In [7]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:


# Merge the DataFrames on the 'title' column
movies = movies.merge(credits, on='title')

In [9]:
movies.shape

(4809, 23)

In [10]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [11]:
#factors needed to recommend movies to users:
#title
#id
#genres
#keywords
#overview
#cast
#crew
movies=movies[['movie_id','title','id','genres','keywords','overview','cast','crew']]

In [12]:
movies.head(1)

,movie_id,title,id,genres,keywords,overview,cast,crew
0,19995,Avatar,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [13]:
movies.isnull().sum()

movie_id    0
title       0
id          0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [14]:
movies.dropna(inplace=True)

In [15]:
movies.isnull().sum()

movie_id    0
title       0
id          0
genres      0
keywords    0
overview    0
cast        0
crew        0
dtype: int64

In [16]:
movies.duplicated().sum()

0

In [17]:
movies.genres

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4804    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                   []
4808                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4806, dtype: object

In [18]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [19]:
#since genres are not in the required format we will create a function to recreate the format....
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#for instance we dont need the above format for our app...we need in the format["action",'adventure','fantasy',....etc]]
import ast 
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
        return L

In [20]:
movies['genres']=movies['genres'].apply(convert)

In [21]:
movies.head(5)
#problem solved for genres section...

,movie_id,title,id,genres,keywords,overview,cast,crew
0,19995,Avatar,19995,[Action],"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,285,[Adventure],"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,206647,[Action],"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,49026,[Action],"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,49529,[Action],"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
movies['keywords']=movies['keywords'].apply(convert)

In [23]:
movies.head(2)
#keywords now are in presentable format...

,movie_id,title,id,genres,keywords,overview,cast,crew
0,19995,Avatar,19995,[Action],[culture clash],"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,285,[Adventure],[ocean],"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [24]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [25]:
#now for cast...we need only the important people to promote the film to user...(for example, top three characters...)
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [26]:
movies['cast']=movies['cast'].apply(convert3)

In [27]:
movies['cast']

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [28]:
movies.head(3)
#now cast is in presentable format ...

,movie_id,title,id,genres,keywords,overview,cast,crew
0,19995,Avatar,19995,[Action],[culture clash],"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,285,[Adventure],[ocean],"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,206647,[Action],[spy],A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [29]:
#now same for the crew
movies['crew'][2]
# I only care for job title director

'[{"credit_id": "54805967c3a36829b5002c41", "department": "Sound", "gender": 2, "id": 153, "job": "Original Music Composer", "name": "Thomas Newman"}, {"credit_id": "52fe4d22c3a368484e1d8d77", "department": "Directing", "gender": 2, "id": 39, "job": "Director", "name": "Sam Mendes"}, {"credit_id": "5677cd99925141691a005333", "department": "Art", "gender": 1, "id": 8384, "job": "Set Decoration", "name": "Anna Pinnock"}, {"credit_id": "52fe4d22c3a368484e1d8d8d", "department": "Writing", "gender": 2, "id": 932, "job": "Screenplay", "name": "John Logan"}, {"credit_id": "562fc9bb92514129fe0006b4", "department": "Writing", "gender": 2, "id": 932, "job": "Story", "name": "John Logan"}, {"credit_id": "5654d41c92514145c3000373", "department": "Art", "gender": 2, "id": 4248, "job": "Production Design", "name": "Dennis Gassner"}, {"credit_id": "52fe4d22c3a368484e1d8d71", "department": "Writing", "gender": 2, "id": 9856, "job": "Characters", "name": "Ian Fleming"}, {"credit_id": "54805989c3a36829ae0022d8", "department": "Editing", "gender": 0, "id": 3904, "job": "Editor", "name": "Lee Smith"}, {"credit_id": "5677df82c3a3681683008748", "department": "Sound", "gender": 2, "id": 7538, "job": "Music Editor", "name": "Bill Bernstein"}, {"credit_id": "5720e370c3a368117e00045b", "department": "Production", "gender": 2, "id": 8784, "job": "Co-Producer", "name": "Daniel Craig"}, {"credit_id": "5522fdd09251416d4a0024b6", "department": "Costume & Make-Up", "gender": 1, "id": 11227, "job": "Costume Design", "name": "Jany Temime"}, {"credit_id": "5677cc9ac3a368167c0089b5", "department": "Production", "gender": 1, "id": 10496, "job": "Casting", "name": "Debbie McWilliams"}, {"credit_id": "52fe4d22c3a368484e1d8d7d", "department": "Production", "gender": 1, "id": 10666, "job": "Producer", "name": "Barbara Broccoli"}, {"credit_id": "5720e3afc3a368117e00046a", "department": "Production", "gender": 0, "id": 11268, "job": "Line Producer", "name": "Roberto Malerba"}, {"credit_id": "5677df58c3a368167c008c82", "department": "Sound", "gender": 0, "id": 40827, "job": "Music Editor", "name": "Peter Clarke"}, {"credit_id": "5677dd1ec3a36816890085d3", "department": "Sound", "gender": 0, "id": 14764, "job": "Sound Designer", "name": "Christopher Assells"}, {"credit_id": "566046b9c3a36875f400323a", "department": "Sound", "gender": 0, "id": 14765, "job": "Supervising Sound Editor", "name": "Per Hallberg"}, {"credit_id": "5677ccab925141691a00530f", "department": "Production", "gender": 0, "id": 36108, "job": "Casting", "name": "Nicole Schmied"}, {"credit_id": "5677cfe4c3a36816850087d2", "department": "Production", "gender": 0, "id": 36108, "job": "Casting Associate", "name": "Nicole Schmied"}, {"credit_id": "562fc984c3a3681b5400e16f", "department": "Writing", "gender": 2, "id": 10783, "job": "Screenplay", "name": "Robert Wade"}, {"credit_id": "562fc9cec3a3681b4b00d168", "department": "Writing", "gender": 2, "id": 10783, "job": "Story", "name": "Robert Wade"}, {"credit_id": "562fc976c3a3681b5c00dd64", "department": "Writing", "gender": 0, "id": 10782, "job": "Screenplay", "name": "Neal Purvis"}, {"credit_id": "562fc9d79251414ad800c103", "department": "Writing", "gender": 0, "id": 10782, "job": "Story", "name": "Neal Purvis"}, {"credit_id": "5720e61d9251414235000477", "department": "Production", "gender": 2, "id": 10876, "job": "Executive Producer", "name": "Callum McDougall"}, {"credit_id": "562fc9a89251414ad800c0fe", "department": "Writing", "gender": 2, "id": 21339, "job": "Screenplay", "name": "Jez Butterworth"}, {"credit_id": "570bd7f2c3a36802a9000412", "department": "Art", "gender": 0, "id": 23425, "job": "Supervising Art Director", "name": "Chris Lowe"}, {"credit_id": "5677e45ac3a368168b0084fd", "department": "Art", "gender": 0, "id": 23491, "job": "Assistant Art Director", "name": "Roxana Alexandru "}, {"credit_id": "5677e29c925141691a00561c", "department": "Crew", "gender": 0, "id": 23774, "job": "Makeup Effects", "name": "Jo Grover"}, {"credit_id": "5677cf8492514179d20088ae", "department": "Production", "gender": 2, "id": 10907, "job": "Casting", "name": "St\\u00e9phane Foenkinos"}, {"credit_id": "5677d7b192514179d20089c6", "department": "Camera", "gender": 2, "id": 61851, "job": "Camera Operator", "name": "Lorenzo Senatore"}, {"credit_id": "5720e6f7925141423000046b", "department": "Production", "gender": 0, "id": 64000, "job": "Line Producer", "name": "Wolfgang Ramml"}, {"credit_id": "5677dfabc3a368168000899f", "department": "Sound", "gender": 2, "id": 66941, "job": "Orchestrator", "name": "J.A.C. Redford"}, {"credit_id": "5720e72e92514142320007fc", "department": "Production", "gender": 0, "id": 81517, "job": "Associate Producer", "name": "Gregg Wilson"}, {"credit_id": "52fe4d22c3a368484e1d8d83", "department": "Production", "gender": 2, "id": 69678, "job": "Producer", "name": "Michael G. Wilson"}, {"credit_id": "5720e325c3a368118100043e", "department": "Production", "gender": 0, "id": 77511, "job": "Line Producer", "name": "Zakaria Alaoui"}, {"credit_id": "548059799251416e7e00265c", "department": "Camera", "gender": 0, "id": 74401, "job": "Director of Photography", "name": "Hoyte van Hoytema"}, {"credit_id": "5677cef792514179db00904d", "department": "Crew", "gender": 0, "id": 239885, "job": "Special Effects Coordinator", "name": "Franco Ragusa"}, {"credit_id": "5677d7e992514179e7008654", "department": "Camera", "gender": 0, "id": 937946, "job": "Camera Operator", "name": "Peter Field"}, {"credit_id": "5677cd21c3a3681680008700", "department": "Art", "gender": 2, "id": 979698, "job": "Art Direction", "name": "Neal Callow"}, {"credit_id": "5677cd5a92514179e30086fb", "department": "Art", "gender": 2, "id": 986687, "job": "Art Direction", "name": "Mark Harris"}, {"credit_id": "5678090392514179e1009958", "department": "Crew", "gender": 0, "id": 1024842, "job": "Visual Effects Editor", "name": "Billy A. Campbell"}, {"credit_id": "5720e6749251414240000470", "department": "Production", "gender": 0, "id": 1026247, "job": "Co-Producer", "name": "Stacy Perskie"}, {"credit_id": "56780a2292514179dd008d18", "department": "Visual Effects", "gender": 0, "id": 1029804, "job": "Visual Effects Producer", "name": "Laura Schultz"}, {"credit_id": "5677e174925141691a0055f1", "department": "Costume & Make-Up", "gender": 0, "id": 1087452, "job": "Key Hair Stylist", "name": "Mari Paz Robles"}, {"credit_id": "5677e0cf9251417845001631", "department": "Costume & Make-Up", "gender": 0, "id": 1099281, "job": "Hairstylist", "name": "Gerardo Perez Arreola"}, {"credit_id": "5677d73b92514179dd008471", "department": "Camera", "gender": 0, "id": 1118711, "job": "Camera Operator", "name": "Kenji Katori"}, {"credit_id": "5677cd3a92514179d2008852", "department": "Art", "gender": 0, "id": 1296445, "job": "Art Direction", "name": "Ben Collins"}, {"credit_id": "5677cfc3c3a3681680008755", "department": "Production", "gender": 0, "id": 1305251, "job": "Casting Associate", "name": "Tusse Lande"}, {"credit_id": "5677e24f92514179e70087da", "department": "Costume & Make-Up", "gender": 0, "id": 1315700, "job": "Makeup Artist", "name": "Donald Mowat"}, {"credit_id": "5677d622c3a368167c008b25", "department": "Costume & Make-Up", "gender": 0, "id": 1319160, "job": "Costume Supervisor", "name": "Ken Crouch"}, {"credit_id": "5677cd0ec3a368168e008f75", "department": "Art", "gender": 0, "id": 1335539, "job": "Art Direction", "name": "Andrew Bennett"}, {"credit_id": "56780833925141691a005c2f", "department": "Visual Effects", "gender": 0, "id": 1338241, "job": "Visual Effects Coordinator", "name": "Sean McGrath"}, {"credit_id": "5677dcc7c3a36816830086cc", "department": "Sound", "gender": 0, "id": 1338372, "job": "Foley", "name": "Dan O\'Connell"}, {"credit_id": "56780ac692514179dd008d31", "department": "Visual Effects", "gender": 0, "id": 1341741, "job": "Visual Effects Supervisor", "name": "Mark Curtis"}, {"credit_id": "5677dd9fc3a368168b0083f0", "department": "Sound", "gender": 2, "id": 1341858, "job": "Sound Re-Recording Mixer", "name": "Gregg Rudloff"}, {"credit_id": "566047029251412204002337", "department": "Directing", "gender": 0, "id": 1342669, "job": "Script Supervisor", "name": "Jayne-Ann Tenggren"}, {"credit_id": "5720e713925141423000046d", "department": "Production", "gender": 0, "id": 1342669, "job": "Associate Producer", "name": "Jayne-Ann Tenggren"}, {"credit_id": "5677dd8792514179db009235", "department": "Sound", "gender": 0, "id": 1345595, "job": "Sound Re-Recording Mixer", "name": "Scott Millan"}, {"credit_id": "5677def192514179e700875b", "department": "Directing", "gender": 0, "id": 1358025, "job": "Script Supervisor", "name": "Nicoletta Mani"}, {"credit_id": "5677dcb0925141691a00552a", "department": "Sound", "gender": 0, "id": 1367493, "job": "Foley", "name": "John T. Cucci"}, {"credit_id": "5677d7ff92514179e300884b", "department": "Camera", "gender": 0, "id": 1377503, "job": "Camera Operator", "name": "Sebastian Meuschel"}, {"credit_id": "5677d94192514179d20089ff", "department": "Camera", "gender": 2, "id": 1388897, "job": "Steadicam Operator", "name": "Julian Morson"}, {"credit_id": "5677dce5c3a36816830086d3", "department": "Sound", "gender": 0, "id": 1389614, "job": "Foley", "name": "Peter Michael Sullivan"}, {"credit_id": "56780a5a92514179e300908d", "department": "Visual Effects", "gender": 0, "id": 1391691, "job": "Visual Effects Producer", "name": "Ken Dailey"}, {"credit_id": "5677dd38c3a368167c008c21", "department": "Sound", "gender": 0, "id": 1392083, "job": "Sound Designer", "name": "Ann Scibelli"}, {"credit_id": "5677d7cd92514179db009178", "department": "Camera", "gender": 0, "id": 1392246, "job": "Camera Operator", "name": "Clive Jackson"}, {"credit_id": "5677de6192514179dd008566", "department": "Directing", "gender": 0, "id": 1392661, "job": "Script Supervisor", "name": "Susie Jones"}, {"credit_id": "5677d98fc3a3681685008904", "department": "Camera", "gender": 2, "id": 1392718, "job": "Still Photographer", "name": "Jasin Boland"}, {"credit_id": "5677cdd8c3a368168b0081e1", "department": "Art", "gender": 0, "id": 1394117, "job": "Art Department Coordinator", "name": "Jennifer Lewicki"}, {"credit_id": "5677e58cc3a3681685008adb", "department": "Art", "gender": 0, "id": 1398089, "job": "Greensman", "name": "Ian Whiteford"}, {"credit_id": "56780a7592514179db0099c4", "department": "Visual Effects", "gender": 0, "id": 1398100, "job": "Visual Effects Producer", "name": "Kilou Picard"}, {"credit_id": "5677d8ba92514179d20089f0", "department": "Camera", "gender": 0, "id": 1399071, "job": "Helicopter Camera", "name": "Hans Bjerno"}, {"credit_id": "5677dd02c3a368167a0091a2", "department": "Editing", "gender": 2, "id": 1399862, "job": "Dialogue Editor", "name": "Daniel Saxlid"}, {"credit_id": "5677e2e1c3a368167c008d1a", "department": "Costume & Make-Up", "gender": 0, "id": 1401126, "job": "Wigmaker", "name": "Alex Rouse"}, {"credit_id": "5678096bc3a368167c0093d2", "department": "Crew", "gender": 0, "id": 1401147, "job": "Visual Effects Editor", "name": "Anik Seguin"}, {"credit_id": "5677dc90c3a368167a009190", "department": "Sound", "gender": 0, "id": 1401631, "job": "ADR & Dubbing", "name": "Michelle Pazer"}, {"credit_id": "5677d75ac3a368167a0090e9", "department": "Camera", "gender": 2, "id": 1403411, "job": "Camera Operator", "name": "Lucas Bielan"}, {"credit_id": "566046d7c3a36875e900359d", "department": "Sound", "gender": 0, "id": 1404212, "job": "Supervising Sound Editor", "name": "Karen Baker Landers"}, {"credit_id": "5677dd519251417845001588", "department": "Sound", "gender": 0, "id": 1404217, "job": "Sound Designer", "name": "Peter Staubli"}, {"credit_id": "5677d8d192514179e1009100", "department": "Camera", "gender": 0, "id": 1404244, "job": "Helicopter Camera", "name": "John Marzano"}, {"credit_id": "5677d927c3a36816850088f2", "department": "Camera", "gender": 0, "id": 1405241, "job": "Helicopter Camera", "name": "Adam Dale"}, {"credit_id": "5677dff292514179e100921a", "department": "Editing", "gender": 0, "id": 1408363, "job": "First Assistant Editor", "name": "Emma McCleave"}, {"credit_id": "5677e191925141784500164f", "department": "Costume & Make-Up", "gender": 0, "id": 1409821, "job": "Makeup Designer", "name": "Naomi Donne"}, {"credit_id": "5677e2b5c3a368168e0092aa", "department": "Crew", "gender": 0, "id": 1411323, "job": "Makeup Effects", "name": "Susan Howard"}, {"credit_id": "5677d869c3a36816850088e3", "department": "Lighting", "gender": 0, "id": 1414096, "job": "Gaffer", "name": "David Smith"}, {"credit_id": "56780712c3a368168b008ace", "department": "Crew", "gender": 0, "id": 1415157, "job": "CG Supervisor", "name": "Joel Green"}, {"credit_id": "567806ba92514179e10098ee", "department": "Crew", "gender": 0, "id": 1425484, "job": "CG Supervisor", "name": "Laurent Hugueniot"}, {"credit_id": "56780a92c3a36816850090af", "department": "Visual Effects", "gender": 0, "id": 1425488, "job": "Visual Effects Producer", "name": "Tim Keene"}, {"credit_id": "5677e087c3a368167a00922b", "department": "Costume & Make-Up", "gender": 0, "id": 1425971, "job": "Hair Designer", "name": "Zoe Tahir"}, {"credit_id": "567808eb92514179e300904a", "department": "Crew", "gender": 0, "id": 1428902, "job": "Visual Effects Editor", "name": "Conor Byrne"}, {"credit_id": "5677e22d925141691a00560d", "department": "Costume & Make-Up", "gender": 0, "id": 1439128, "job": "Makeup Artist", "name": "Charlotte Hayward"}, {"credit_id": "5677cf3fc3a36816850087c1", "department": "Visual Effects", "gender": 0, "id": 1442137, "job": "Animation Supervisor", "name": "Catherine Mullan"}, {"credit_id": "56780988c3a3681683008e99", "department": "Crew", "gender": 0, "id": 1447617, "job": "Visual Effects Editor", "name": "Crystal Hadcroft"}, {"credit_id": "5677e0ec925141691a0055d6", "department": "Costume & Make-Up", "gender": 0, "id": 1458416, "job": "Hairstylist", "name": "Francesca Crowder"}, {"credit_id": "5677cf2892514179dd008356", "department": "Visual Effects", "gender": 0, "id": 1459878, "job": "Animation Director", "name": "Marlene Chazot"}, {"credit_id": "5678091d92514179db009985", "department": "Crew", "gender": 0, "id": 1459899, "job": "Visual Effects Editor", "name": "Struan Farquhar"}, {"credit_id": "56780731c3a3681680009013", "department": "Crew", "gender": 0, "id": 1459925, "job": "CG Supervisor", "name": "Daniel Pastore"}, {"credit_id": "5677d969c3a368168b00834a", "department": "Camera", "gender": 0, "id": 1470167, "job": "Still Photographer", "name": "Jonathan Olley"}, {"credit_id": "5677e48dc3a368167a0092c8", "department": "Art", "gender": 0, "id": 1472773, "job": "Assistant Art Director", "name": "Sami Gaidi"}, {"credit_id": "5751eed59251416b60000637", "department": "Production", "gender": 2, "id": 1477203, "job": "Co-Producer", "name": "Luca Marco Paracels"}, {"credit_id": "5677e157c3a36816800089ee", "department": "Costume & Make-Up", "gender": 0, "id": 1480629, "job": "Key Hair Stylist", "name": "Luca Vannella"}, {"credit_id": "56780b0e925141691a005c8f", "department": "Visual Effects", "gender": 0, "id": 1483141, "job": "Visual Effects Supervisor", "name": "Stuart Bullen"}, {"credit_id": "582f29fa925141022e003a74", "department": "Sound", "gender": 0, "id": 1494824, "job": "Sound Effects Editor", "name": "Russell Edwards"}, {"credit_id": "5677d63dc3a368167a0090b4", "department": "Costume & Make-Up", "gender": 0, "id": 1510431, "job": "Costume Supervisor", "name": "Stefano De Nardis"}, {"credit_id": "5677d79992514179d20089c2", "department": "Camera", "gender": 0, "id": 1512767, "job": "Camera Operator", "name": "Luis David Sansans"}, {"credit_id": "5677d609c3a368168000881a", "department": "Costume & Make-Up", "gender": 0, "id": 1545912, "job": "Costume Supervisor", "name": "Abderrahim Benkhayi"}, {"credit_id": "5677d66cc3a368167a0090be", "department": "Costume & Make-Up", "gender": 0, "id": 1545913, "job": "Set Costumer", "name": "Rachid Aadassi"}, {"credit_id": "5677da26c3a368167a009139", "department": "Camera", "gender": 0, "id": 1545995, "job": "Additional Camera", "name": "Carlos De Carvalho"}, {"credit_id": "5677d5bec3a368167c008b13", "department": "Costume & Make-Up", "gender": 0, "id": 1546747, "job": "Assistant Costume Designer", "name": "Vivienne Jones"}, {"credit_id": "5677dfcac3a368168300875b", "department": "Editing", "gender": 0, "id": 1548406, "job": "Digital Intermediate", "name": "Kim Honeyman"}, {"credit_id": "5677e105c3a368168b00846d", "department": "Costume & Make-Up", "gender": 0, "id": 1550637, "job": "Hairstylist", "name": "Kathryn Fa"}, {"credit_id": "5677ce0c9251417845001384", "department": "Crew", "gender": 0, "id": 1551770, "job": "Carpenter", "name": "Paul Duff"}, {"credit_id": "5677ce5192514179e300871b", "department": "Crew", "gender": 0, "id": 1551771, "job": "Property Master", "name": "Ben Wilkinson"}, {"credit_id": "5677cec292514179dd00834d", "department": "Crew", "gender": 0, "id": 1551772, "job": "Special Effects Coordinator", "name": "Lynne Corbould"}, {"credit_id": "5677cf57c3a368168e008fcc", "department": "Production", "gender": 0, "id": 1551773, "job": "Casting", "name": "Amal El-Farfachi"}, {"credit_id": "5677cf99c3a368168b00821d", "department": "Production", "gender": 0, "id": 1551774, "job": "Casting Associate", "name": "Celebrity Booker"}, {"credit_id": "5677cfadc3a368167c008a30", "department": "Production", "gender": 0, "id": 1551775, "job": "Casting Associate", "name": "Lucy Hellier"}, {"credit_id": "5677d5a392514179db00911d", "department": "Costume & Make-Up", "gender": 0, "id": 1551777, "job": "Assistant Costume Designer", "name": "Richard Davies"}, {"credit_id": "5677dd6bc3a368168b0083e2", "department": "Sound", "gender": 0, "id": 1551789, "job": "Sound Effects Editor", "name": "Ando Johnson"}, {"credit_id": "5677de2dc3a3681683008713", "department": "Crew", "gender": 0, "id": 1551791, "job": "Armorer", "name": "Greg Corke"}, {"credit_id": "5677de8a92514179e10091d9", "department": "Production", "gender": 0, "id": 1551796, "job": "Researcher", "name": "Amin Rharda"}, {"credit_id": "5677dea9c3a368168e00921c", "department": "Crew", "gender": 0, "id": 1551797, "job": "Armorer", "name": "Joss Skottowe"}, {"credit_id": "5677e11c92514179dd0085e3", "department": "Costume & Make-Up", "gender": 0, "id": 1551798, "job": "Hairstylist", "name": "Joseph Koniak"}, {"credit_id": "5677e1b19251417845001657", "department": "Costume & Make-Up", "gender": 0, "id": 1551800, "job": "Makeup Artist", "name": "Thal\\u00eda Echeveste"}, {"credit_id": "5677e1c7c3a368167c008cd8", "department": "Costume & Make-Up", "gender": 0, "id": 1551801, "job": "Makeup Artist", "name": "Charlie Hounslow"}, {"credit_id": "5677e1e592514179d2008b7b", "department": "Costume & Make-Up", "gender": 0, "id": 1551802, "job": "Makeup Artist", "name": "Lucy Friend"}, {"credit_id": "5677e1fa92514179e1009265", "department": "Costume & Make-Up", "gender": 0, "id": 1551803, "job": "Makeup Artist", "name": "Yelska Labrada"}, {"credit_id": "5677e20fc3a36816830087d9", "department": "Costume & Make-Up", "gender": 0, "id": 1551804, "job": "Makeup Artist", "name": "Ana Gabriela Quinonez"}, {"credit_id": "5677e32d9251417845001683", "department": "Production", "gender": 0, "id": 1551807, "job": "Researcher", "name": "Gina De Ferrer"}, {"credit_id": "5677e47592514179e10092dd", "department": "Art", "gender": 0, "id": 1551809, "job": "Assistant Art Director", "name": "Lydia Fry"}, {"credit_id": "5677e4a492514179db009373", "department": "Art", "gender": 0, "id": 1551810, "job": "Assistant Art Director", "name": "Liam Georgensen"}, {"credit_id": "5677e4bb92514179dd00868a", "department": "Art", "gender": 0, "id": 1551811, "job": "Assistant Art Director", "name": "Hugh McClelland"}, {"credit_id": "5677e53092514179db00938e", "department": "Crew", "gender": 0, "id": 1551812, "job": "Carpenter", "name": "John Allen"}, {"credit_id": "5677e547c3a368167a0092ef", "department": "Crew", "gender": 0, "id": 1551813, "job": "Carpenter", "name": "Eddie Murphy"}, {"credit_id": "567806e092514179dd008c84", "department": "Crew", "gender": 0, "id": 155

In [30]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i["job"] == "Director":
            L.append(i["name"])
            break  # Assuming you only want to append the first director
    return L

In [31]:
movies['crew'] = movies['crew'].apply(lambda x: fetch_director(x) if x else [])

In [32]:
movies.head(3)

,movie_id,title,id,genres,keywords,overview,cast,crew
0,19995,Avatar,19995,[Action],[culture clash],"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,285,[Adventure],[ocean],"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,206647,[Action],[spy],A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [33]:
movies['overview'][0]
#since the overview is in string form and we want it to be in list form so we can concatenate with others to form  tags...thus,
movies['overview'].apply(lambda x:x.split())
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [34]:
movies.head(2)

,movie_id,title,id,genres,keywords,overview,cast,crew
0,19995,Avatar,19995,[Action],[culture clash],"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,285,[Adventure],[ocean],"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [35]:
#cleaning spaces-transformation
movies['crew'].head(1)
#so here james cameroon shld be in the form jamescameroon
movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4806, dtype: object

In [36]:

movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

0        [SamWorthington, ZoeSaldana, SigourneyWeaver]
1           [JohnnyDepp, OrlandoBloom, KeiraKnightley]
2            [DanielCraig, ChristophWaltz, LéaSeydoux]
3            [ChristianBale, MichaelCaine, GaryOldman]
4          [TaylorKitsch, LynnCollins, SamanthaMorton]
                             ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt]
4805         [EdwardBurns, KerryBishé, MarshaDietlein]
4806           [EricMabius, KristinBooth, CrystalLowe]
4807            [DanielHenney, ElizaCoupe, BillPaxton]
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman]
Name: cast, Length: 4806, dtype: object

In [37]:
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x] if isinstance(x, list) else None)

movies['keywords'][0]

['cultureclash']

In [38]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x] if isinstance(x, list) else None)
movies['genres'][0]

['Action']

In [39]:
movies.head(3)

,movie_id,title,id,genres,keywords,overview,cast,crew
0,19995,Avatar,19995,[Action],[cultureclash],"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,285,[Adventure],[ocean],"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,206647,[Action],[spy],"[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [40]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
movies.head(2)

,movie_id,title,id,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,19995,[Action],[cultureclash],"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,285,[Adventure],[ocean],"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [41]:
new_df=movies[['title','movie_id','tags']]
new_df

,title,movie_id,tags
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,206647,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney..."
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,El Mariachi,9367,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,Newlyweds,72766,NaN
4806,"Signed, Sealed, Delivered",231617,"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,Shanghai Calling,126186,NaN
4808,My Date with Drew,25975,"[Ever, since, the, second, grade, when, he, fi..."

In [42]:
# Assuming new_df is your DataFrame containing the data you provided

# Convert lists in 'tags' column to strings
new_df['tags'] = new_df['tags'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x)

C:\Users\somaa\AppData\Local\Temp\ipykernel_11388\3541810376.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x)

In [43]:
new_df['tags'].head
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action cultureclash Sam Worthington Zoe Saldana Sigourney Weaver James Cameron'

In [44]:
new_df['tags'] = new_df['tags'].apply(lambda x: str(x).lower())

C:\Users\somaa\AppData\Local\Temp\ipykernel_11388\958511873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: str(x).lower())

In [45]:
new_df.head(2)

,title,movie_id,tags
0,Avatar,19995,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,285,"captain barbossa, long believed to be dead, ha..."

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(new_df['tags']).toarray()

In [47]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
len(cv.get_feature_names_out())

5000

In [49]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'], dtype=object)

In [50]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\somaa\appdata\roaming\python\python311\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\somaa\appdata\roaming\python\python311\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\somaa\appdata\roaming\python\python311\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\somaa\appdata\roaming\python\python311\site-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in c:\users\somaa\appdata\roaming\python\python311\site-packages (from nltk) (4.66.2)
Requirement already satisfied: colorama in c:\users\somaa\appdata\roaming\python\python311\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [51]:
import nltk

In [52]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [53]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
        return " ".join(y)

In [54]:
#example of stemming....
#if i have words [like love,loving,loved,lover]
#it will return love(reducing the dimensionality of the dataset)
['loving','loved','lover']
['love','love','love']
ps.stem('loving')

'love'

In [55]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\somaa\AppData\Local\Temp\ipykernel_11388\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [56]:
new_df['tags'].head

<bound method NDFrame.head of 0             in
1        captain
2              a
3         follow
4           john
          ...
4804          el
4805         nan
4806    "signed,
4807         nan
4808        ever
Name: tags, Length: 4806, dtype: object>

In [57]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'], dtype=object)

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
cosine_similarity(vectors)

array([[1.        , 0.        , 0.08104409, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.03329636, 0.        ,
        0.        ],
       [0.08104409, 0.        , 1.        , ..., 0.02900074, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03329636, 0.02900074, ..., 1.        , 0.        ,
        0.03966818],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.03966818, 0.        ,
        1.        ]])

In [60]:
cosine_similarity(vectors).shape

(4806, 4806)

In [61]:
similarity=cosine_similarity(vectors)

In [62]:
similarity[1]
#it basically gave me the comparison values of movie 1 to all the other movies in the dataset in the values between 0 to 1....1 being the most similar type of movie ....

array([0.        , 1.        , 0.        , ..., 0.03329636, 0.        ,
       0.        ])

In [63]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]#this will give the the similarity of first movie with respect to all the other movie according to their index values

[(2405, 0.21239769762143662),
 (3606, 0.20982172726556325),
 (94, 0.1904761904761905),
 (1673, 0.1851640199545103),
 (942, 0.17817416127494962)]

In [64]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]]['title'])

In [65]:
recommend('John Carter')

Get Carter
The Inhabited Island
The Great Raid
Circle
Captain America: The First Avenger

In [66]:
new_df

                                         title  movie_id      tags
0                                       Avatar     19995        in
1     Pirates of the Caribbean: At World's End       285   captain
2                                      Spectre    206647         a
3                        The Dark Knight Rises     49026    follow
4                                  John Carter     49529      john
...                                        ...       ...       ...
4804                               El Mariachi      9367        el
4805                                 Newlyweds     72766       nan
4806                 Signed, Sealed, Delivered    231617  "signed,
4807                          Shanghai Calling    126186       nan
4808                         My Date with Drew     25975      ever

[4806 rows x 3 columns]

In [67]:
recommend('John Carter')

Get Carter
The Inhabited Island
The Great Raid
Circle
Captain America: The First Avenger

In [68]:
import pickle

In [69]:
pickle.dump(new_df,open('movies.pkl', 'wb'))

In [70]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [71]:
new_df.to_dict()

{'title': {0: 'Avatar',
  1: "Pirates of the Caribbean: At World's End",
  2: 'Spectre',
  3: 'The Dark Knight Rises',
  4: 'John Carter',
  5: 'Spider-Man 3',
  6: 'Tangled',
  7: 'Avengers: Age of Ultron',
  8: 'Harry Potter and the Half-Blood Prince',
  9: 'Batman v Superman: Dawn of Justice',
  10: 'Superman Returns',
  11: 'Quantum of Solace',
  12: "Pirates of the Caribbean: Dead Man's Chest",
  13: 'The Lone Ranger',
  14: 'Man of Steel',
  15: 'The Chronicles of Narnia: Prince Caspian',
  16: 'The Avengers',
  17: 'Pirates of the Caribbean: On Stranger Tides',
  18: 'Men in Black 3',
  19: 'The Hobbit: The Battle of the Five Armies',
  20: 'The Amazing Spider-Man',
  21: 'Robin Hood',
  22: 'The Hobbit: The Desolation of Smaug',
  23: 'The Golden Compass',
  24: 'King Kong',
  25: 'Titanic',
  26: 'Captain America: Civil War',
  27: 'Battleship',
  28: 'Jurassic World',
  29: 'Skyfall',
  30: 'Spider-Man 2',
  31: 'Iron Man 3',
  32: 'Alice in Wonderland',
  33: 'X-Men: The Last Stand',
  34: 'Monsters University',
  35: 'Transformers: Revenge of the Fallen',
  36: 'Transformers: Age of Extinction',
  37: 'Oz: The Great and Powerful',
  38: 'The Amazing Spider-Man 2',
  39: 'TRON: Legacy',
  40: 'Cars 2',
  41: 'Green Lantern',
  42: 'Toy Story 3',
  43: 'Terminator Salvation',
  44: 'Furious 7',
  45: 'World War Z',
  46: 'X-Men: Days of Future Past',
  47: 'Star Trek Into Darkness',
  48: 'Jack the Giant Slayer',
  49: 'The Great Gatsby',
  50: 'Prince of Persia: The Sands of Time',
  51: 'Pacific Rim',
  52: 'Transformers: Dark of the Moon',
  53: 'Indiana Jones and the Kingdom of the Crystal Skull',
  54: 'The Good Dinosaur',
  55: 'Brave',
  56: 'Star Trek Beyond',
  57: 'WALL·E',
  58: 'Rush Hour 3',
  59: '2012',
  60: 'A Christmas Carol',
  61: 'Jupiter Ascending',
  62: 'The Legend of Tarzan',
  63: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  64: 'X-Men: Apocalypse',
  65: 'The Dark Knight',
  66: 'Up',
  67: 'Monsters vs Aliens',
  68: 'Iron Man',
  69: 'Hugo',
  70: 'Wild Wild West',
  71: 'The Mummy: Tomb of the Dragon Emperor',
  72: 'Suicide Squad',
  73: 'Evan Almighty',
  74: 'Edge of Tomorrow',
  75: 'Waterworld',
  76: 'G.I. Joe: The Rise of Cobra',
  77: 'Inside Out',
  78: 'The Jungle Book',
  79: 'Iron Man 2',
  80: 'Snow White and the Huntsman',
  81: 'Maleficent',
  82: 'Dawn of the Planet of the Apes',
  83: 'The Lovers',
  84: '47 Ronin',
  85: 'Captain America: The Winter Soldier',
  86: 'Shrek Forever After',
  87: 'Tomorrowland',
  88: 'Big Hero 6',
  89: 'Wreck-It Ralph',
  90: 'The Polar Express',
  91: 'Independence Day: Resurgence',
  92: 'How to Train Your Dragon',
  93: 'Terminator 3: Rise of the Machines',
  94: 'Guardians of the Galaxy',
  95: 'Interstellar',
  96: 'Inception',
  97: 'Shin Godzilla',
  98: 'The Hobbit: An Unexpected Journey',
  99: 'The Fast and the Furious',
  100: 'The Curious Case of Benjamin Button',
  101: 'X-Men: First Class',
  102: 'The Hunger Games: Mockingjay - Part 2',
  103: "The Sorcerer's Apprentice",
  104: 'Poseidon',
  105: 'Alice Through the Looking Glass',
  106: 'Shrek the Third',
  107: 'Warcraft',
  108: 'Terminator Genisys',
  109: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
  110: 'Pearl Harbor',
  111: 'Transformers',
  112: 'Alexander',
  113: 'Harry Potter and the Order of the Phoenix',
  114: 'Harry Potter and the Goblet of Fire',
  115: 'Hancock',
  116: 'I Am Legend',
  117: 'Charlie and the Chocolate Factory',
  118: 'Ratatouille',
  119: 'Batman Begins',
  120: 'Madagascar: Escape 2 Africa',
  121: 'Night at the Museum: Battle of the Smithsonian',
  122: 'X-Men Origins: Wolverine',
  123: 'The Matrix Revolutions',
  124: 'Frozen',
  125: 'The Matrix Reloaded',
  126: 'Thor: The Dark World',
  127: 'Mad Max: Fury Road',
  128: 'Angels & Demons',
  129: 'Thor',
  130: 'Bolt',
  131: 'G-Force',
  132: 'Wrath of the Titans',
  133: 'Dark Shadows',
  134: 'Mission: Impossible - Rogue Nation',
  135: 'The Wolfman',
  136: 'Bee Movie',
  137: 'Kung Fu Panda 2',
  138: 'The Last Airbender',
  139: 'Mission: Impossible III',
  140: 'White House Down',
  141: 'Mars Needs Moms',
  142: 'Flushed Away',
  143: 'Pan',
  144: 'Mr. Peabody & Sherman',
  145: 'Troy',
  146: "Madagascar 3: Europe's Most Wanted",
  147: 'Die Another Day',
  148: 'Ghostbusters',
  149: 'Armageddon',
  150: 'Men in Black II',
  151: 'Beowulf',
  152: 'Kung Fu Panda 3',
  153: 'Mission: Impossible - Ghost Protocol',
  154: 'Rise of the Guardians',
  155: 'Fun with Dick and Jane',
  156: 'The Last Samurai',
  157: 'Exodus: Gods and Kings',
  158: 'Star Trek',
  159: 'Spider-Man',
  160: 'How to Train Your Dragon 2',
  161: 'Gods of Egypt',
  162: 'Stealth',
  163: 'Watchmen',
  164: 'Lethal Weapon 4',
  165: 'Hulk',
  166: 'G.I. Joe: Retaliation',
  167: 'Sahara',
  168: 'Final Fantasy: The Spirits Within',
  169: 'Captain America: The First Avenger',
  170: 'The World Is Not Enough',
  171: 'Master and Commander: The Far Side of the World',
  172: 'The Twilight Saga: Breaking Dawn - Part 2',
  173: 'Happy Feet Two',
  174: 'The Incredible Hulk',
  175: 'The BFG',
  176: 'The Revenant',
  177: 'Turbo',
  178: 'Rango',
  179: 'Penguins of Madagascar',
  180: 'The Bourne Ultimatum',
  181: 'Kung Fu Panda',
  182: 'Ant-Man',
  183: 'The Hunger Games: Catching Fire',
  184: 'Home',
  185: 'War of the Worlds',
  186: 'Bad Boys II',
  187: 'Puss in Boots',
  188: 'Salt',
  189: 'Noah',
  190: 'The Adventures of Tintin',
  191: 'Harry Potter and the Prisoner of Azkaban',
  192: 'Australia',
  193: 'After Earth',
  194: 'Dinosaur',
  195: 'Night at the Museum: Secret of the Tomb',
  196: 'Megamind',
  197: "Harry Potter and the Philosopher's Stone",
  198: 'R.I.P.D.',
  199: 'Pirates of the Caribbean: The Curse of the Black Pearl',
  200: 'The Hunger Games: Mockingjay - Part 1',
  201: 'The Da Vinci Code',
  202: 'Rio 2',
  203: 'X2',
  204: 'Fast Five',
  205: 'Sherlock Holmes: A Game of Shadows',
  206: 'Clash of the Titans',
  207: 'Total Recall',
  208: 'The 13th Warrior',
  209: 'The Bourne Legacy',
  210: 'Batman & Robin',
  211: 'How the Grinch Stole Christmas',
  212: 'The Day After Tomorrow',
  213: 'Mission: Impossible II',
  214: 'The Perfect Storm',
  215: 'Fantastic 4: Rise of the Silver Surfer',
  216: 'Life of Pi',
  217: 'Ghost Rider',
  218: 'Jason Bourne',
  219: "Charlie's Angels: Full Throttle",
  220: 'Prometheus',
  221: 'Stuart Little 2',
  222: 'Elysium',
  223: 'The Chronicles of Riddick',
  224: 'RoboCop',
  225: 'Speed Racer',
  226: 'How Do You Know',
  227: 'Knight and Day',
  228: 'Oblivion',
  229: 'Star Wars: Episode III - Revenge of the Sith',
  230: 'Star Wars: Episode II - Attack of the Clones',
  231: 'Monsters, Inc.',
  232: 'The Wolverine',
  233: 'Star Wars: Episode I - The Phantom Menace',
  234: 'The Croods',
  235: 'Asterix at the Olympic Games',
  236: 'Windtalkers',
  237: "The Huntsman: Winter's War",
  238: 'Teenage Mutant Ninja Turtles',
  239: 'Gravity',
  240: "Dante's Peak",
  241: 'Teenage Mutant Ninja Turtles: Out of the Shadows',
  242: 'Fantastic Four',
  243: 'Night at the Museum',
  244: 'San Andreas',
  245: 'Tomorrow Never Dies',
  246: 'The Patriot',
  247: "Ocean's Twelve",
  248: 'Mr. & Mrs. Smith',
  249: 'Insurgent',
  250: 'The Aviator',
  251: "Gulliver's Travels",
  252: 'The Green Hornet',
  253: '300: Rise of an Empire',
  254: 'The Smurfs',
  255: 'Home on the Range',
  256: 'Allegiant',
  257: 'Real Steel',
  258: 'The Smurfs 2',
  259: 'Speed 2: Cruise Control',
  260: "Ender's Game",
  261: 'Live Free or Die Hard',
  262: 'The Lord of the Rings: The Fellowship of the Ring',
  263: 'Around the World in 80 Days',
  264: 'Ali',
  265: 'The Cat in the Hat',
  266: 'I, Robot',
  267: 'Kingdom of Heaven',
  268: 'Stuart Little',
  269: 'The Princess and the Frog',
  270: 'The Martian',
  271: 'The Island',
  272: 'Town & Country',
  273: 'Gone in Sixty Seconds',
  274: 'Gladiator',
  275: 'Minority Report',
  276: 'Harry Potter and the Chamber of Secrets',
  277: 'Casino Royale',
  278: 'Planet of the Apes',
  279: 'Terminator 2: Judgment Day',
  280: 'Public Enemies',
  281: 'American Gangster',
  282: 'True Lies',
  283: 'The Taking of Pelham 1 2 3',
  284: 'Little Fockers',
  285: 'The Other Guys',
  286: 'Eraser',
  287: 'Django Unchained',
  288: 'The Hunchback of Notre Dame',
  289: "The Emperor's New Groove",
  290: 'The Expendables 2',
  291: 'National Treasure',
  292: 'Eragon',
  293: 'Where the Wild Things Are',
  294: 'Epic',
  295: 'The Tourist',
  296: 'End of Days',
  297: 'Blood Diamond',
  298: 'The Wolf of Wall Street',
  299: 'Batman Forever',
  300: 'Starship Troopers',
  301: 'Cloud Atlas',
  302: "Legend of the Guardians: The Owls of Ga'Hoole",
  303: 'Catwoman',
  304: 'Hercules',
  305: 'Treasure Planet',
  306: 'Land of the Lost',
  307: 'The Expendables 3',
  308: 'Point Break',
  309: 'Son of the Mask',
  310: 'In the Heart of the Sea',
  311: 'The Adventures of Pluto Nash',
  312: 'Green Zone',
  313: 'The Peanuts Movie',
  314: 'The Spanish Prisoner',
  315: 'The Mummy Returns',
  316: 'Gangs of New York',
  317: 'The Flowers of War',
  318: "Surf's Up",
  319: 'The Stepford Wives',
  320: 'Black Hawk Down',
  321: 'The Campaign',
  322: 'The Fifth Element',
  323: 'Sex and the City 2',
  324: 'The Road to El Dorado',
  325: 'Ice Age: Continental Drift',
  326: 'Cinderella',
  327: 'The Lovely Bones',
  328: 'Finding Nemo',
  329: 'The Lord of the Rings: The Return of the King',
  330: 'The Lord of the Rings: The Two Towers',
  331: 'Seventh Son',
  332: 'Lara Croft: Tomb Raider',
  333: 'Transcendence',
  334: 'Jurassic Park III',
  335: 'Rise of the Planet of the Apes',
  336: 'The Spiderwick Chronicles',
  337: 'A Good Day to Die Hard',
  338: 'The Alamo',
  339: 'The Incredibles',
  340: 'Cutthroat Island',
  341: 'Percy Jackson & the Olympians: The Lightning Thief',
  342: 'Men in Black',
  343: 'Toy Story 2',
  344: 'Unstoppable',
  345: 'Rush Hour 2',
  346: 'What Lies Beneath',
  347: 'Cloudy with a Chance of Meatballs',
  348: 'Ice Age: Dawn of the Dinosaurs',
  349: 'The Secret Life of Walter Mitty',
  350: "Charlie's Angels",
  351: 'The Departed',
  352: 'Mulan',
  353: 'Tropic Thunder',
  354: 'The Girl with the Dragon Tattoo',
  355: 'Die Hard: With a Vengeance',
  356: 'Sherlock Holmes',
  357: 'Ben-Hur',
  358: 'Atlantis: The Lost Empire',
  359: 'Alvin and the Chipmunks: The Road Chip',
  360: 'Valkyrie',
  361: "You Don't Mess with the Zohan",
  362: 'Pixels',
  363: 'A.I. Artificial Intelligence',
  364: 'The Haunted Mansion',
  365: 'Contact',
  366: 'Hollow Man',
  367: 'The Interpreter',
  368: 'Percy Jackson: Sea of Monsters',
  369: 'Lara Croft Tomb Raider: The Cradle of Life',
  370: 'Now You See Me 2',
  371: 'The Saint',
  372: 'Spy Game',
  373: 'Mission to Mars',
  374: 'Rio',
  375: 'Bicentennial Man',
  376: 'Volcano',
  377: "The Devil's Own",
  378: 'K-19: The Widowmaker',
  379: 'Conan the Barbarian',
  380: 'Cinderella Man',
  381: 'The Nutcracker: The Untold Story',
  382: 'Seabiscuit',
  383: 'Twister',
  384: 'Cast Away',
  385: 'Happy Feet',
  386: 'The Bourne Supremacy',
  387: 'Air Force One',
  388: "Ocean's Eleven",
  389: 'The Three Musketeers',
  390: 'Hotel Transylvania',
  391: 'Enchanted',
  392: 'Safe House',
  393: '102 Dalmatians',
  394: 'Tower Heist',
  395: 'The Holiday',
  396: 'Enemy of the State',
  397: "It's Complicated",
  398: "Ocean's Thirteen",
  399: 'Open Season',
  400: 'Divergent',
  401: 'Enemy at the Gates',
  402: 'The Rundown',
  403: 'Last Action Hero',
  404: 'Memoirs of a Geisha',
  405: 'The Fast and the Furious: Tokyo Drift',
  406: 'Arthur Christmas',
  407: 'Meet Joe Black',
  408: 'Collateral Damage',
  409: 'All That Jazz',
  410: 'Mirror Mirror',
  411: 'Scott Pilgrim vs. the World',
  412: 'The Core',
  413: 'Nutty Professor II: The Klumps',
  414: 'Scooby-Doo',
  415: 'Dredd',
  416: 'Click',
  417: 'Creepshow',
  418: 'Cats & Dogs 2 : The Revenge of Kitty Galore',
  419: 'Jumper',
  420: 'Hellboy II: The Golden Army',
  421: 'Zodiac',
  422: 'The 6th Day',
  423: 'Bruce Almighty',
  424: 'The Expendables',
  425: 'Mission: Impossible',
  426: 'The Hunger Games',
  427: 'The Hangover Part II',
  428: 'Batman Returns',
  429: 'Over the Hedge',
  430: 'Lilo & Stitch',
  431: "Charlotte's Web",
  432: 'Deep Impact',
  433: 'RED 2',
  434: 'The Longest Yard',
  435: 'Alvin and the Chipmunks: Chipwrecked',
  436: 'Grown Ups 2',
  437: 'Get Smart',
  438: "Something's Gotta Give",
  439: 'Shutter Island',
  440: 'Four Christmases',
  441: 'Robots',
  442: 'Face/Off',
  443: 'Bedtime Stories',
  444: 'Road to Perdition',
  445: 'Just Go with It',
  446: 'Con Air',
  447: 'Eagle Eye',
  448: 'Cold Mountain',
  449: 'The Book of Eli',
  450: 'Flubber',
  451: 'The Haunting',
  452: 'Space Jam',
  453: 'The Pink Panther',
  454: 'The Day the Earth Stood Still',
  455: 'Conspiracy Theory',
  456: 'Fury',
  457: 'Six Days Seven Nights',
  458: 'Yogi Bear',
  459: 'Spirit: Stallion of the Cimarron',
  460: 'Zookeeper',
  461: 'Lost in Space',
  462: 'The Manchurian Candidate',
  463: 'Déjà Vu',
  464: 'Hotel Transylvania 2',
  465: 'Fantasia 2000',
  466: 'The Time Machine',
  467: 'Mighty Joe Young',
  468: 'Swordfish',
  469: 'The Legend of Zorro',
  470: 'What Dreams May Come',
  471: 'Little Nicky',
  472: 'The Brothers Grimm',
  473: 'Mars Attacks!',
  474: 'Evolution',
  475: 'The Edge',
  476: 'Surrogates',
  477: 'Thirteen Days',
  478: 'Daylight',
  479: 'Walking With Dinosaurs',
  480: 'Battlefield Earth',
  481: 'Looney Tunes: Back in Action',
  482: 'Nine',
  483: 'Timeline',
  484: 'The Postman',
  485: 'Babe: Pig in the City',
  486: 'The Last Witch Hunter',
  487: 'Red Planet',
  488: 'Arthur and the Invisibles',
  489: 'Oceans',
  490: 'A Sound of Thunder',
  491: 'Pompeii',
  492: 'Top Cat Begins',
  493: 'A Beautiful Mind',
  494: 'The Lion King',
  495: 'Journey 2: The Mysterious Island',
  496: 'Cloudy with a Chance of Meatballs 2',
  497: 'Red Dragon',
  498: 'Hidalgo',
  499: 'Jack and Jill',
  500: '2 Fast 2 Furious',
  501: 'The Little Prince',
  502: 'The Invasion',
  503: 'The Adventures of Rocky & Bullwinkle',
  504: 'The Secret Life of Pets',
  505: 'The League of Extraordinary Gentlemen',
  506: 'Despicable Me 2',
  507: 'Independence Day',
  508: 'The Lost World: Jurassic Park',
  509: 'Madagascar',
  510: 'Children of Men',
  511: 'X-Men',
  512: 'Wanted',
  513: 'The Rock',
  514: 'Ice Age: The Meltdown',
  515: '50 First Dates',
  516: 'Hairspray',
  517: 'Exorcist: The Beginning',
  518: 'Inspector Gadget',
  519: 'Now You See Me',
  520: 'Grown Ups',
  521: 'The Terminal',
  522: 'Hotel for Dogs',
  523: 'Vertical Limit',
  524: "Charlie Wilson's War",
  525: 'Shark Tale',
  526: 'Dreamgirls',
  527: 'Be Cool',
  528: 'Munich',
  529: 'Tears of the Sun',
  530: 'Killers',
  531: 'The Man from U.N.C.L.E.',
  532: 'Spanglish',
  533: 'Monster House',
  534: 'Bandits',
  535: 'First Knight',
  536: 'Anna and the King',
  537: 'Immortals',
  538: 'Hostage',
  539: 'Titan A.E.',
  540: 'Hollywood Homicide',
  541: 'Soldier',
  542: 'Carriers',
  543: 'Monkeybone',
  544: 'Flight of the Phoenix',
  545: 'Unbreakable',
  546: 'Minions',
  547: 'Sucker Punch',
  548: 'Snake Eyes',
  549: 'Sphere',
  550: 'The Angry Birds Movie',
  551: "Fool's Gold",
  552: 'Funny People',
  553: 'The Kingdom',
  554: 'Talladega Nights: The Ballad of Ricky Bobby',
  555: 'Dr. Dolittle 2',
  556: 'Braveheart',
  557: 'Jarhead',
  558: 'The Simpsons Movie',
  559: 'The Majestic',
  560: 'Driven',
  561: 'Two Brothers',
  562: 'The Village',
  563: 'Doctor Dolittle',
  564: 'Signs',
  565: 'Shrek 2',
  566: 'Cars',
  567: 'Runaway Bride',
  568: 'xXx',
  569: 'The SpongeBob Movie: Sponge Out of Water',
  570: 'Ransom',
  571: 'Inglourious Basterds',
  572: 'Hook',
  573: 'Die Hard 2',
  574: 'S.W.A.T.',
  575: 'Vanilla Sky',
  576: 'Lady in the Water',
  577: 'AVP: Alien vs. Predator',
  578: 'Alvin and the Chipmunks: The Squeakquel',
  579: 'We Were Soldiers',
  580: 'Olympus Has Fallen',
  581: 'Star Trek: Insurrection',
  582: 'Battle: Los Angeles',
  583: 'Big Fish',
  584: 'Wolf',
  585: 'War Horse',
  586: 'The Monuments Men',
  587: 'The Abyss',
  588: 'Wall Street: Money Never Sleeps',
  589: 'Dracula Untold',
  590: 'The Siege',
  591: 'Stardust',
  592: 'Seven Years in Tibet',
  593: 'The Dilemma',
  594: 'Bad Company',
  595: 'Doom',
  596: 'I Spy',
  597: 'Underworld: Awakening',
  598: 'Rock of Ages',
  599: "Hart's War",
  600: 'Killer Elite',
  601: 'Rollerball',
  602: 'Ballistic: Ecks vs. Sever',
  603: 'Hard Rain',
  604: 'Osmosis Jones',
  605: "Legends of Oz: Dorothy's Return",
  606: 'Blackhat',
  607: 'Sky Captain and the World of Tomorrow',
  608: 'Basic Instinct 2',
  609: 'Escape Plan',
  610: 'The Legend of Hercules',
  611: 'The Sum of All Fears',
  612: 'The Twilight Saga: Eclipse',
  613: 'The Score',
  614: 'Despicable Me',
  615: 'Money Train',
  616: 'Ted 2',
  617: 'Agora',
  618: 'Mystery Men',
  619: 'Hall Pass',
  620: 'The Insider',
  621: 'The Finest Hours',
  622: 'Body of Lies',
  623: 'Dinner for Schmucks',
  624: 'Abraham Lincoln: Vampire Hunter',
  625: 'Entrapment',
  626: 'The X Files',
  627: 'The Last Legion',
  628: 'Saving Private Ryan',
  629: 'Need for Speed',
  630: 'What Women Want',
  631: 'Ice Age',
  632: 'Dreamcatcher',
  633: 'Lincoln',
  634: 'The Matrix',
  635: 'Apollo 13',
  636: 'The Santa Clause 2',
  637: 'Les Misérables',
  638: "You've Got Mail",
  639: 'Step Brothers',
  640: 'The Mask of Zorro',
  641: 'Due Date',
  642: 'Unbroken',
  643: 'Space Cowboys',
  644: 'Cliffhanger',
  645: 'Broken Arrow',
  646: 'The Kid',
  647: 'World Trade Center',
  648: 'Mona Lisa Smile',
  649: 'The Dictator',
  650: 'Eyes Wide Shut',
  651: 'Annie',
  652: 'Focus',
  653: 'This Means War',
  654: 'Blade: Trinity',
  655: 'Red Dawn',
  656: 'Primary Colors',
  657: 'Resident Evil: Retribution',
  658: 'Death Race',
  659: 'The Long Kiss Goodnight',
  660: 'Proof of Life',
  661: 'Zathura: A Space Adventure',
  662: 'Fight Club',
  663: 'We Are Marshall',
  664: 'Hudson Hawk',
  665: 'Lucky Numbers',
  666: 'I, Frankenstein',
  667: 'Oliver Twist',
  668: 'Elektra',
  669: 'Sin City: A Dame to Kill For',
  670: 'Random Hearts',
  671: 'Everest',
  672: 'Perfume: The Story of a Murderer',
  673: 'Austin Powers in Goldmember',
  674: 'Astro Boy',
  675: 'Jurassic Park',
  676: 'Wyatt Earp',
  677: 'Clear and Present Danger',
  678: 'Dragon Blade',
  679: 'Little Man',
  680: 'U-571',
  681: 'The American President',
  682: 'The Love Guru',
  683: '3000 Miles to Graceland',
  684: 'The Hateful Eight',
  685: 'Blades of Glory',
  686: 'Hop',
  687: '300',
  688: 'Meet the Fockers',
  689: 'Marley & Me',
  690: 'The Green Mile',
  691: 'Wild Hogs',
  692: 'Chicken Little',
  693: 'Gone Girl',
  694: 'The Bourne Identity',
  695: 'GoldenEye',
  696: "The General's Daughter",
  697: 'The Truman Show',
  698: 'The Prince of Egypt',
  699: 'Daddy Day Care',
  700: '2 Guns',
  701: 'Cats & Dogs',
  702: 'The Italian Job',
  703: 'Two Weeks Notice',
  704: 'Antz',
  705: 'Couples Retreat',
  706: 'Days of Thunder',
  707: 'Cheaper by the Dozen 2',
  708: 'Maze Runner: The Scorch Trials',
  709: 'Eat Pray Love',
  710: 'The Family Man',
  711: 'RED',
  712: 'Any Given Sunday',
  713: 'The Horse Whisperer',
  714: 'Collateral',
  715: 'The Scorpion King',
  716: 'Ladder 49',
  717: 'Jack Reacher',
  718: 'Deep Blue Sea',
  719: 'This Is It',
  720: 'Contagion',
  721: 'Kangaroo Jack',
  722: 'Coraline',
  723: 'The Happening',
  724: 'Man on Fire',
  725: 'The Shaggy Dog',
  726: 'Starsky & Hutch',
  727: 'Jingle All the Way',
  728: 'Hellboy',
  729: 'A Civil Action',
  730: 'ParaNorman',
  731: 'The Jackal',
  732: 'Paycheck',
  733: 'Up Close & Personal',
  734: 'The Tale of Despereaux',
  735: 'The Tuxedo',

In [77]:
import pickle

# Assuming new_df is your DataFrame
new_df_dict = new_df.to_dict()

# Pickle the dictionary
with open('movie_dict.pkl', 'wb') as f:
    pickle.dump(new_df_dict, f)

In [78]:
movies_dict

<bound method DataFrame.to_dict of                                          title  movie_id      tags
0                                       Avatar     19995        in
1     Pirates of the Caribbean: At World's End       285   captain
2                                      Spectre    206647         a
3                        The Dark Knight Rises     49026    follow
4                                  John Carter     49529      john
...                                        ...       ...       ...
4804                               El Mariachi      9367        el
4805                                 Newlyweds     72766       nan
4806                 Signed, Sealed, Delivered    231617  "signed,
4807                          Shanghai Calling    126186       nan
4808                         My Date with Drew     25975      ever

[4806 rows x 3 columns]>